# Generated by Django 4.1.1 on 2022-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coretool_verbosename'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretool',
            name='description',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
