# Generated by Django 4.1.1 on 2022-10-10 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_orgcore_brandcore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandCore',
            new_name='CoreBrand',
        ),
        migrations.RenameModel(
            old_name='OrgCore',
            new_name='CoreOrg',
        ),
    ]
