# Generated by Django 4.1.1 on 2022-10-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_corebrand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebrand',
            name='logo',
            field=models.FileField(blank=True, upload_to='uploads/brands/logos'),
        ),
    ]
