# Generated by Django 4.1.1 on 2022-10-11 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('datetime', models.DateTimeField()),
                ('locationmapslink', models.CharField(blank=True, max_length=300, verbose_name='Google Maps Link')),
                ('status', models.CharField(choices=[('AN', 'Anunciado'), ('EV', 'En Venta'), ('VT', 'Venta Terminada'), ('AR', 'Archivado')], default='AN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('is_active', models.BooleanField(default=False)),
                ('q_sells', models.IntegerField(default=0, verbose_name='Ventas')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.event', verbose_name='Evento')),
            ],
        ),
        migrations.CreateModel(
            name='RegToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=300)),
                ('q_tickets', models.IntegerField(verbose_name='Tickets')),
                ('reference', models.CharField(default='none', max_length=150)),
                ('client', models.CharField(default='none', max_length=50)),
                ('total', models.IntegerField(default='0', verbose_name='Total')),
                ('created', models.DateTimeField(auto_now=True)),
                ('staff_asigned', models.CharField(default='none', max_length=30)),
                ('comprobante', models.FileField(blank=True, upload_to='uploads/comprobantes/quimera/')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencía'), ('DEPOSIT', 'Deposíto')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('RE', 'Rechazado'), ('AP', 'Aprobado'), ('AR', 'Archivado')], default='PE', max_length=2)),
                ('cash_pay', models.BooleanField(blank=True, default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.event')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.fase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('hash', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Hash Id')),
                ('client', models.CharField(default='none', max_length=50)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status_export', models.BooleanField(default=True)),
                ('use', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.event')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.fase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.seller')),
                ('ticketrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.ticketrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentTicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.event')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.seller')),
                ('ticketrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oldcore.ticketrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
