# Generated by Django 4.1.1 on 2022-10-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldcore', '0002_fase_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'permissions': (('can_view_admin', 'To see admin pages'), ('can_view_staff', 'To see staff pages'), ('can_view_rp', 'To see rp PAGES'))},
        ),
    ]
