# Generated by Django 4.1.1 on 2022-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldcore', '0004_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='name',
            field=models.CharField(default='name_default', max_length=40),
        ),
    ]
